FROM python:3.8

WORKDIR /backend

COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . ./

EXPOSE 8100

# CMD ["uvicorn", "src.app:app", "--reload", "--host", "0.0.0.0", "--port", "8100"]
